version: '3.9'

services:
  db:
    image: postgres:15.1-alpine
    restart: always
    environment:
      POSTGRES_DB: staff-bot
      POSTGRES_USER: staff-bot-admin
      POSTGRES_PASSWORD: '@mir1990'
    volumes:
      - db_data_dev:/var/lib/postgresql/data
    ports:
      - target: 5432
        published: 6000
        protocol: tcp
        mode: host

volumes:
  db_data_dev:
    driver: local
