START = "start"
SHOW_HELP = "show_help"
REGISTER = "register"
QUESTIONS = "questions"
BACK_TO_MENU = "back_to_bot_menu"
EDIT = "edit"
STAT = "stat"
ADMIN = "admin"
HEAD = "head"
TASK = "get_user_task"

ADMIN_PROMPT_ADD_QUESTION_BOX = "admin_prompt_add_question_box"
ADMIN_SHOW_USERS_LIST = "admin_show_users_list"
ADMIN_SHOW_USERS_LIST_BUTTONS = "admin_show_users_list_buttons"
ADMIN_ADD_HEAD = "admin_add_head"
ADMIN_SHOW_QUESTIONS_BOX_TO_REMOVE = "admin_show_questions_box_to_remove"
ADMIN_SHOW_QUESTION_BOXES_FOR_STAT = "admin_show_question_boxes_for_stat"

HEAD_ADD_TASK = "head_add_task"
HEAD_SHOW_MARKED_TASKS = "show_marked_tasks"
HEAD_APPROVE_TASK = "head_approve_task"
HEAD_SHOW_TASKS_TO_REMOVE = "head_show_tasks_to_remove"
HEAD_REMOVE_TASK = "head_remove_task"
HEAD_SHOW_QUESTIONS_BOX_TO_REMOVE = "head_show_questions_box_to_remove"
HEAD_SHOW_QUESTION_BOXES_FOR_STAT = "head_show_question_boxes_for_stat"
HEAD_SHOW_QUESTION_BOX_STAT = "head_show_question_box_stat"
HEAD_REMOVE_QUESTION_BOX = "head_remove_question_box"

BACK_TO_ADMIN_ACTIONS = "back_to_admin_actions"
BACK_TO_TASKS_ACTIONS = "back_to_tasks_actions"
BACK_TO_HEAD_ACTIONS = "back_to_head_actions"

NEXT_QUESTION = "next"
SKIP_QUESTIONS = "skip_questions_of_questions_box"
QUIT_QUESTIONS = "quit_questions_box"
START_QUESTIONS = "start_questions_quiz"
CANCEL_QUESTIONS = "cancel_questions"
BACK_TO_STAT = "back_to_stat"
QUESTIONS_HISTORY = "history"
NEXT_QUESTIONS_PAGE = "next_questions_page"
PREV_QUESTIONS_PAGE = "prev_questions_page"
REGISTER_ADMIN = "register_as_an_admin"
REMAINING_TASKS = "remaining_tasks"
DONE_TASKS = "done_tasks"
TOTAL_TASKS_SCORE = "total_tasks_score"
SUBMIT_TASK = "submit_task"

SUBMIT_TASK_PREFIX = "submit_task_prefix"
TASK_INFORMATION_PREFIX = "task_information_prefix"
REMOVE_QUESTION_BOX_PREFIX = "remove_question_box_prefix"
GET_QUESTION_BOX_STAT_PREFIX = "get_question_box_stat_prefix"
