from enum import Enum


class RegisterStates(Enum):
    ASK_FOR_STUDENT_CODE = "ASK_FOR_STUDENT_CODE"
    REGISTER_STUDENT_CODE = "REGISTER_STUDENT_CODE"
    REGISTER_NICKNAME = "REGISTER_NICKNAME"


class EditStates(Enum):
    ASK_TO_EDIT_WHAT = "ASK_TO_EDIT_WHAT"
    EDIT_DECIDER = "EDIT_DECIDER"
    EDIT_NICKNAME = "EDIT_NICKNAME"
    EDIT_STUDENT_CODE = "EDIT_STUDENT_CODE"


class QuestionStates(Enum):
    SHOW_QUESTIONS = "SHOW_QUESTIONS"
    ANSWER_VALIDATOR = "ANSWER_VALIDATOR"


class StatStates(Enum):
    SHOW_STAT = "SHOW_STAT"
    DECIDER = "DECIDER"
    SELECT_QUESTION_BOX = "SELECT_QUESTION_BOX"
