from enum import Enum


class RegisterStates(Enum):
    ASK_FOR_STUDENT_CODE = "ASK_FOR_STUDENT_CODE"
    REGISTER_STUDENT_CODE = "REGISTER_STUDENT_CODE"
    REGISTER_TEAM = "REGISTER_TEAM"
    REGISTER_NICKNAME = "REGISTER_NICKNAME"


class EditStates(Enum):
    ASK_TO_EDIT_WHAT = "ASK_TO_EDIT_WHAT"
    EDIT_DECIDER = "EDIT_DECIDER"
    EDIT_NICKNAME = "EDIT_NICKNAME"
    EDIT_STUDENT_CODE = "EDIT_STUDENT_CODE"
    EDIT_TEAM = "EDIT_TEAM"


class QuestionStates(Enum):
    SHOW_QUESTIONS = "SHOW_QUESTIONS"
    ANSWER_VALIDATOR = "ANSWER_VALIDATOR"


class StatStates(Enum):
    SHOW_STAT = "SHOW_STAT"
    DECIDER = "DECIDER"
    SELECT_QUESTION_BOX = "SELECT_QUESTION_BOX"


class AdminStates(Enum):
    SHOW_ADMIN_ACTIONS = "SHOW_ADMIN_ACTIONS"
    REGISTER_USER_AS_AN_ADMIN = "REGISTER_USER_AS_AN_ADMIN"
    ADMIN_ACTIONS = "ADMIN_ACTIONS"


class TaskStates(Enum):
    SHOW_TASKS_ACTIONS = "SHOW_TASKS_ACTIONS"
    TASK_ACTION_DECIDER = "TASK_ACTION_DECIDER"
    SHOW_TASK_INFORMATION = "SHOW_TASK_INFORMATION"


class HeadStates(Enum):
    HEAD_ACTION_DECIDER = "HEAD_ACTION_DECIDER"
    HEAD_ADD_TASK = "HEAD_ADD_TASK"
